vendor_name = Xendit
base_url = https://api.xendit.co
Disbursement  = /v2/payouts
VirtualAccount = /payment_requests
RetailOutlet = /payment_requests
DirectDebit = /payment_requests
QRCode = /payment_requests

content_type = application/json
authorization = Basic eG5kX2RldmVsb3BtZW50X25DQWxzbHhiRFZjeGRDOGhQYzJucmFQM25SbktGQXBkZmk1eEQ2aDgyMzZ4eDNWSTBTQzJldkZQQk5nQlBOOg==