INSERT INTO public.chartofaccount_comp (id) VALUES (10000);
INSERT INTO public.chartofaccount_comp (id) VALUES (11000);
INSERT INTO public.chartofaccount_comp (id) VALUES (11100);
INSERT INTO public.chartofaccount_comp (id) VALUES (11200);
INSERT INTO public.chartofaccount_comp (id) VALUES (12000);
INSERT INTO public.chartofaccount_comp (id) VALUES (12100);
INSERT INTO public.chartofaccount_comp (id) VALUES (12200);
INSERT INTO public.chartofaccount_comp (id) VALUES (19000);
INSERT INTO public.chartofaccount_comp (id) VALUES (40000);
INSERT INTO public.chartofaccount_comp (id) VALUES (41000);
INSERT INTO public.chartofaccount_comp (id) VALUES (41010);
INSERT INTO public.chartofaccount_comp (id) VALUES (41020);
INSERT INTO public.chartofaccount_comp (id) VALUES (42000);
INSERT INTO public.chartofaccount_comp (id) VALUES (42010);
INSERT INTO public.chartofaccount_comp (id) VALUES (42020);
INSERT INTO public.chartofaccount_comp (id) VALUES (43000);
INSERT INTO public.chartofaccount_comp (id) VALUES (43010);
INSERT INTO public.chartofaccount_comp (id) VALUES (43020);
INSERT INTO public.chartofaccount_comp (id) VALUES (43099);
INSERT INTO public.chartofaccount_comp (id) VALUES (44000);
INSERT INTO public.chartofaccount_comp (id) VALUES (49000);
INSERT INTO public.chartofaccount_comp (id) VALUES (60000);
INSERT INTO public.chartofaccount_comp (id) VALUES (61000);
INSERT INTO public.chartofaccount_comp (id) VALUES (62000);
INSERT INTO public.chartofaccount_comp (id) VALUES (63000);
INSERT INTO public.chartofaccount_comp (id) VALUES (63400);
INSERT INTO public.chartofaccount_comp (id) VALUES (64000);
INSERT INTO public.chartofaccount_comp (id) VALUES (65000);
INSERT INTO public.chartofaccount_comp (id) VALUES (65100);
INSERT INTO public.chartofaccount_comp (id) VALUES (65200);
INSERT INTO public.chartofaccount_comp (id) VALUES (65400);
INSERT INTO public.chartofaccount_comp (id) VALUES (66000);
INSERT INTO public.chartofaccount_comp (id) VALUES (66100);
INSERT INTO public.chartofaccount_comp (id) VALUES (66200);
INSERT INTO public.chartofaccount_comp (id) VALUES (66300);
INSERT INTO public.chartofaccount_comp (id) VALUES (67000);
INSERT INTO public.chartofaccount_comp (id) VALUES (68000);
INSERT INTO public.chartofaccount_comp (id) VALUES (69000);

INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (10000, 10000, 'Saldo', '    ',0);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (11000, 11000, 'Rekening Bank', '    ',0);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (11100, 11100, 'Rekening Bank - Khusus', 'Saldo yang tersimpan di rekening bank, untuk kebutuhan/pembiayaan khusus, seperti rekening untuk zakat fithrah, hanya untuk fakir miskin saja.',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (11200, 11200, 'Rekening Bank - Umum', 'Saldo yang tersimpan di rekening bank, dan memang jelas bebas digunakan untuk institusi sesuai aturan yang berlaku,',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (12000, 12000, 'Kas', '    ',0);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (12100, 12100, 'Kas - Umum', 'Saldo yang disimpan pengurus, untuk kebutuhan umum seperti saldo kotak amal Jumat',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (12200, 12200, 'Kas - Khusus', 'Saldo yang disimpan pengurus, untuk kebutuhan khusus seperti saldo kas untuk operasional dan konsumsi petugas',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (19000, 19000, 'Saldo Lainnya', 'Saldo lainnya dalam bentuk non cash yang dihargai dalam rupiah.',0);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (40000, 40000, 'Penerimaan', '    ',0);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (41000, 41000, 'Donasi Institusi', '    ',0);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (41010, 41010, 'Donasi Pemerintah', 'Donasi dari pemerintah misalnya seperti BLT',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (41020, 41020, 'Donasi Swasta (CSR)', 'Donasi dari swasta seperti dari dana CSR atau sumbangan karyawan.',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (42000, 42000, 'Donasi Individu', '    ',0);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (42010, 42010, 'Donasi Individu Tercatat', 'Donasi dari individu yang tercatat sumber dan identitas pengirim',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (42020, 42020, 'Donasi Anonymous', 'Donasi dari individu yang tidak diketahui sumber nya atau dinyatakan anonymous.',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (43000, 43000, 'Penerimaan Hasil Usaha', 'Rekapitulasi segala Penerimaan institusi dari hasil usaha baik usaha internal maupun kerjasama',0);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (43010, 43010, 'Hasil penjualan', 'Penerimaan institusi dari kegiatan penjualan barang',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (43020, 43020, 'Hasil upah jasa', 'Penerimaan institusi dari kegiatan upah atau jasa',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (43099, 43099, 'Bonus/ Hasil usaha lain-lain', 'Penerimaan institusi dari usaha lain-lain atau bonus/komisi',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (44000, 44000, 'Iuran', 'Penerimaan dalam bentuk iuran rutin, seperti iuran kebersihan.',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (49000, 49000, 'Penerimaan Lainnya', 'Penerimaan yang belum bisa dikategorikan.',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (60000, 60000, 'Pengeluaran', '    ',0);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (61000, 61000, 'Penyaluran donasi', 'Pembiayaan dalam bentuk menyalurkan kembali donasi yang diterima kepada pihak lain, seperti penyaluran zakat maal kepada para mustahiq.',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (62000, 62000, 'Gaji dan Honor', 'Pembiayaan untuk gaji dan honor, seperti gaji marbot, gaji keamanan, honor pembicaran, honor ustadz, moderator',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (63000, 63000, 'Biaya Umum', 'Biaya untuk kebutuhan umum seperti administrasi, iuran kebersihan, dan keamanan',0);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (63400, 63400, 'Biaya Administrasi', 'Pembiayaan administrasi seperti biaya pengurusan akta notaris, biaya transfer dll',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (64000, 64000, 'Biaya Sewa dan Jasa', 'Pembiayaan sewa ruangan, alat, sewa jasa, termasuk jasa biaya tranportasi, kurir, akomodasi',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (65000, 65000, 'Pengeluaran Kegiatan/Program', 'Pengeluaran yang terkait dengan kegiatan atau program institusi',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (65100, 65100, 'Biaya Publikasi', 'Pembiayaan untuk publikasi program, kegiatan',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (65200, 65200, 'Biaya Konsumsi', 'Pembiayaan untuk konsumsi kegiatan/program',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (65400, 65400, 'Biaya Peralatan', 'Pembiayaan pembeliaan peralatan untuk kegiatan atau untuk kepentingan ins',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (66000, 66000, 'Pengeluaran Umum/Rutin', 'Segala pembiayaan/ pengeluaran yang rutin terjadi atau tidak terikat program/kegiatan khusus',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (66100, 66100, 'Biaya Bahan Habis Pakai', 'Pembiayaan bahan habis pakai yang rutin digunakan, seperti printer, sabun, cairan pembersih.',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (66200, 66200, 'Biaya Operasional', 'Pembiayaan rutin operasional, seperti listrik, air, internet',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (66300, 66300, 'Biaya Perawatan', 'Pembiayaan terkait perawatan aset institusi, termasuk cat tembok rutin.',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (67000, 67000, 'Pengembangan SDM/ Pelatihan', 'Pembiayaan Pengembangan Sumber daya Insitutusi, seperti pelatihan, beasiswa, buku.',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (68000, 68000, 'Biaya Renovasi/ Reparasi', 'Pembiayaan renovasi, perbaikan kerusakan bangunan, alat, kendaraan',1);
INSERT INTO public.chartofaccount_impl (id, code, name, description, isVisible) VALUES (69000, 69000, 'Biaya-biaya Lainnya', 'Pembiayaan lain yang belum terkategorikan atau belum jelas kategorinya',1);