INSERT INTO program_comp (idprogram) VALUES(458134636);
INSERT INTO program_comp (idprogram) VALUES(1349531118);
INSERT INTO program_comp (idprogram) VALUES(1343279926);
INSERT INTO program_comp (idprogram) VALUES(1270189464);
INSERT INTO program_comp (idprogram) VALUES(1843226349);

INSERT INTO program_impl (idprogram, name, description, target, partner, logoUrl, executionDate) VALUES(458134636,'Belanja Untuk Mereka','Program Belanja dari Samuel Charity yang bertujuan untuk dapat membantu warga sekitar dalam mendapatkan sayur hidroponik dan daging berkualitas','Warga Cakung','UNESCA','https://images.freeimages.com/images/large-previews/13e/my-cat-1363423.jpg',NULL);
INSERT INTO program_impl (idprogram, name, description, target, partner, logoUrl, executionDate) VALUES(1349531118,'Makanan Kita Makanan Meraka','Makanan Kita Makanan Meraka adalah program untuk makanan sehat dan bergizi untuk santri raudhotul muhibbin',' Santri Raudhotul Muhibbin','IHO','https://images.freeimages.com/images/large-previews/aff/winter-in-holland-1396288.jpg',NULL);
INSERT INTO program_impl (idprogram, name, description, target, partner, logoUrl, executionDate) VALUES(1343279926,'Khitanan Massal','Khitanan Massal adalah program dari DKM Masjid Al-Jabbar yang menggratiskan khitanan untuk 40 orang warga. Bekerjasama dengan dokter bedah dari Rumah Sakit Umum Koja. Sebelum proses khitanan terdapat games dan nonton film anak-anak muslim muslimah.',' Usia 4 - 12 tahun','Dokter RS Koja','https://images.freeimages.com/images/large-previews/03b/abstract-series-13-1529920.jpg',NULL);
INSERT INTO program_impl (idprogram, name, description, target, partner, logoUrl, executionDate) VALUES(1270189464,'Sumur Desa Rawabening','Program untuk mendirikan sumur baru di desa rawabening untuk warga desa','warga desa rawabening','Bupati Rawabening','https://images.freeimages.com/images/large-previews/315/a-kayak-rider-passing-by-1641874.jpg',NULL);
INSERT INTO program_impl (idprogram, name, description, target, partner, logoUrl, executionDate) VALUES(1843226349,'Peduli Mata Mereka','Program periksa mata, penyediaan kacamata dan penyembuhan katarak untuk warga desa rawabakti', 'Warga rawa bakti', 'UNESCA','https://images.freeimages.com/images/large-previews/655/colorful-architecture-1-1216925.jpg',NULL);
